on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  go-tests:
    name: Run Terratest Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 #v4
      - uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 #v3
        with:
          terraform_version: 1.2.5
          terraform_wrapper: false
      - run: |
          terraform init
          terraform validate
        working-directory: modules/sqs/examples/
